#######################################################
# Wake Up Platform                                    #
# (c) Telefonica Digital, 2013 - All rights reserved  #
# License: GNU Affero V3 (see LICENSE file)           #
# Fernando Rodríguez Sela <frsela@tid.es>             #
#######################################################

.PHONY = provision_data

provision_data:
	@echo "Provisioning operators data on REDIS database ..."
	@./wakeup_provisionnetworks
	@echo "Done!"
